name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: blueocean-parent-$NEXT_PATCH_VERSION
exclude-lables:
  - internal
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
template: |
  ## What’s Changed

  $CHANGES
